app_admin_tpos:
    resource: "@AppBundle/Resources/config/routing/tpos.yml"
    prefix:   /admin/tpos

app_admin_terminal_payment:
    resource: "@AppBundle/Resources/config/routing/terminalpayment.yml"
    prefix:   /admin/terminal-payment
    
app_admin_payments:
    resource: "@AppBundle/Resources/config/routing/tpayments.yml"
    prefix:   /admin/payments
    
app_admin_post:
    resource: "@AppBundle/Resources/config/routing/wspost.yml"
    prefix:   /admin/post

app_admin_media:
    resource: "@AppBundle/Resources/config/routing/wsmedia.yml"
    prefix:   /admin/media

app_admin_bincode:
    resource: "@AppBundle/Resources/config/routing/bincode.yml"
    prefix:   /admin/bincode
    
app_admin_binbank:
    resource: "@AppBundle/Resources/config/routing/binbank.yml"
    prefix:   /admin/binbank

app_admin_broker:
    resource: "@AppBundle/Resources/config/routing/broker.yml"
    prefix:   /admin/broker

app_admin_agency:
    resource: "@AppBundle/Resources/config/routing/tagency.yml"
    prefix:   /admin/agency

app_admin_tsubgroup:
    resource: "@AppBundle/Resources/config/routing/tsubgroup.yml"
    prefix:   /admin/tsubgroup

app_admin_tpurchase:
    resource: "@AppBundle/Resources/config/routing/tpurchase.yml"
    prefix:   /admin/tpurchase
    
app_admin_tgroup:
    resource: "@AppBundle/Resources/config/routing/tgroup.yml"
    prefix:   admin/tgroup
